name: Android APK Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build APK (Debug)
        run: ./gradlew assembleDebug
        working-directory: Sherlock-Android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Sherlock-Android-APK
          path: Sherlock-Android/app/build/outputs/apk/debug/*.apk

